version: "3.9"
services:
  portfolio:
    build:
      dockerfile: Dockerfile
      context: .
      #target: development-build-stage
    #env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - ./:/portfolio
    restart: "always"